server:
  port: 9004 #端口
eureka:
  client:
    #register-with-eureka: false #eureka 是否是一个register,必须作为eureka-server
    #fetch-registry: false #eureka 必须当成一个服务server
    service-url:
      # defaultZone: http://localhost:8761/eureka #eureka 注册到本身eureka服务上,注册服务(单机版)eureka本身也是client
      defaultZone: http://localhost:8761/eureka
  #server: # 一个节点配置
      #waitTimeInMsWhenSyncEmpty: 0

# Another method is specifiying a service-route and configuring a Ribbon client for the serviceId (doing so requires disabling Eureka support in Ribbon — see above for more information), as shown in the following example:
# 另一种方法是指定服务路由，并为Service ID配置一个色带客户端（这样做需要在Enguly-*中禁用Eurka支持），见下面的更多信息，如下面的示例所示：
zuul:
  ignoredServices: '*' # 所有的微服务 ignored, 拒绝
  routes:
    users: #当前路由唯一
      path: /user-path/** #使用当前路径名称2 eg: /user-path/* = /user-path/x ; /user-path/** == /user-path/x/x/..
      serviceId: microservice-provider-user # 代理当前微服务1
      stripPrefix: true

ribbon:
  eureka:
    enabled: false #禁用eureka

microservice-provider-user:
  ribbon:
    listOfServers: http://localhost:8001,http://localhost:8000