server:
  port: 9005 #端口
eureka:
  client:
    #register-with-eureka: false #eureka 是否是一个register,必须作为eureka-server
    #fetch-registry: false #eureka 必须当成一个服务server
    service-url:
      # defaultZone: http://localhost:8761/eureka #eureka 注册到本身eureka服务上,注册服务(单机版)eureka本身也是client
      defaultZone: http://localhost:8761/eureka
  #server: # 一个节点配置
      #waitTimeInMsWhenSyncEmpty: 0

# GET /routes  访问 project-name:prot/foutes 可以获取所有的代理
# eg: GET /routes { /stores/**: "http://localhost:8081" }
# GET /routes/details 访问 project-name:prot/foutes 可以获取所有的代理详情
# eg: GET /routes/details
#{
#  "/stores/**": {
#    "id": "stores",
#    "fullPath": "/stores/**",
#    "location": "http://localhost:8081",
#    "path": "/**",
#    "prefix": "/stores",
#    "retryable": false,
#    "customSensitiveHeaders": false,
#    "prefixStripped": true
#  }
#}

# 兼容旧服务,切换新服务
# eg: /first 访问
# eg: /second 访问
# eg: /third 访问
# eg: /** 其余访问
zuul:
  routes:
    first:
      path: /first/**
      url: http://first.example.com
    second:
      path: /second/**
      url: forward:/second
    third:
      path: /third/**
      url: forward:/3rd
    legacy:
      path: /**
      url: http://legacy.example.com