server:
  port: 7902
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #注册eureka服务节点
      #defaultZone: http://user:password@localhost:8761/eureka #注册eureka服务节点,带密码注册
  instance:
    prefer-ip-address: true # 开启ip访问. (默认主机名访问)
    #主机名:主机ip:port
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    health-check-url: http://localhost:8761/eureka
spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing

# 配置ribbon 使用的微服务,application名称添加.
microservice-provider-user:
  ribbon:
    # NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    # 微服务加权
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule