spring:
  application:
    name: microservice-provider-user-mybatis #项目名称
# 日志,以及日志登记
logging:
  level:
    #root: DEBUG
    com.itmuch.cloud: DEBUG
server:
  port: 8101
spring:
  datasource:
    name: mysql_dev
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://rm-bp12f42am0qr84g0upo.mysql.rds.aliyuncs.com:3306/cashloan_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root_db
      password: ckUFy7FB3lajrZz2S55iqtGmKSvGdXkS
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#mybatis 配置
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.itmuch.cloud

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check